name: Test and Release DevContainer Feature

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy feature to .devcontainer directory
        run: |
          cp -r src/claude-code .devcontainer/features/claude-code

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test DevContainer Feature
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/claude-code
          cacheFrom: ghcr.io/${{ github.repository_owner }}/claude-code:latest
          configFile: ./.devcontainer/devcontainer.json
          runCmd: |
            # Verify Node.js is available
            node --version
            npm --version

            # Check if the package is installed
            npm list -g @anthropic-ai/claude-code

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish DevContainer Feature
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          features-namespace: ${{ github.repository_owner }}
          base-path-to-features: "./src"
