name: Test and Release DevContainer Feature

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test DevContainer Feature
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./test/.devcontainer/devcontainer.json
          runCmd: |
            # Verify Node.js is available
            node --version
            npm --version

            # Check if the package is installed globally (since that's our default now)
            npm list -g @anthropic-ai/claude-code || echo "Package not found in global npm list, checking with require..."

            # Try to require the package
            node -e "try { require('@anthropic-ai/claude-code'); console.log('✅ @anthropic-ai/claude-code successfully installed and can be imported'); } catch(e) { console.error('❌ Failed to import @anthropic-ai/claude-code:', e.message); process.exit(1); }"

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish DevContainer Feature
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
